### ISSUE TITLE
algosdk should offer native TypeScript support

### ISSUE THREAD

**Issue by lepidotteri** [algorand/js-algorand-sdk#265]
Currently:

-  it is notoriously hard to import and bundle correctly the library in existing TS applications, even with popular tools such as Webpack and regardless of their environment targets (node, etc.)
- nobody has even put together officially TS definition files for such a vitally important library for the Algorand ecosystem

The time is long overdue for the team (e.g. @jasonpaulos @JasonWeathersby) to offer a TypeScript-first AlgoSDK for the Web3 JavaScript ecosystem

**Comment by codemaster101** [comment]
I agree completely. Since most of the development for firms these days is in TypeScript (and more and more firms are choosing TS over JS) it seems like a basic support system. Writing our own type definitions for every blockchain which does not support TypeScript is taxing.

**Comment by jasonpaulos** [comment]
@lepidotteri thanks for bringing this up. I agree that native TypeScript support would be a major improvement for algosdk and we are currently planning for v2 of the package to be rewritten in TypeScript (as well as contain many other improvements).

In the meantime, I think it's worth pointing out that @robert-zaremba has submitted #245, which contains a type definitions file for algosdk. We haven't yet decided if want to merge it here since it would be difficult to maintain consistent type definitions in a separate file, but this would be a good resource for anyone who needs type definitions immediately.

**Comment by robert-zaremba** [comment]
Yes, our most up-to date TS typings is available here:
 https://github.com/scale-it/algorand-builder/tree/master/packages/types-algosdk

We are using it internally. Probably will be good to release it in npm. Let me know and we can do it.

**Comment by codemaster101** [comment]
@robert-zaremba I would be really happy if you guys could push it to NPM! Would make life much much easier!

**Comment by robert-zaremba** [comment]
DONE! 
We released the TypeScript typings for `js-algorand-sdk. 
All instructions are available in the README file: https://www.npmjs.com/package/@algorand-builder/types-algosdk

**Comment by lepidotteri** [comment]
> DONE!
> We released the TypeScript typings for `js-algorand-sdk.
> All instructions are available in the README file: https://www.npmjs.com/package/@algorand-builder/types-algosdk

Great! Next up, rewrite the whole library from scratch in TS

**Comment by ian-algorand** [comment]
Closing this issue for now as it doesn't seem there are any additional action items. If you'd like to continue the discussion, check out https://forum.algorand.org/

Thanks!
