### ISSUE TITLE
How to support an external Key Management System with Algorand?

### ISSUE THREAD

**Issue by codemaster101** [algorand/js-algorand-sdk#266]
Hi, I went through the documentation and much of the code base but could not find an example or a reference to adding our own signers on top of a sign class. We support our own external key signing system which does not expose the private keys, and we would like to support that for Algorand as well. 

Maybe an example or Class implementation like this, where we could provide our own signer would be great. 

An example: 
https://github.com/terra-project/terra.js/wiki/Keys#custom-key-implementation

Also, would be great if the SDK can expose functions to generate accounts from Public Keys instead of Mnemonics or Mnemonics generated from private keys. As, again, most of the Key management systems in the crypto space do not expose the private keys and sign transactions inside.

If, by mistake, I have missed something and these implementations already exist, can someone point me to where it is (documentation/code etc.) or an example would be great.

**Comment by jasonpaulos** [comment]
Hi @codemaster101, it sounds like you want something similar to [kmd](https://developer.algorand.org/docs/reference/cli/kmd/), which is Algorand's external key management utility. This package contains a kmd client which lets an external kmd instance sign transactions with [Kmd.signTransaction](https://github.com/algorand/js-algorand-sdk/blob/263fd5dd3fd65a38c4c82fd06504ba7795be70fe/src/client/kmd.js#L243-L268) without the client knowing anything about the private key. Here is the kmd endpoint that it connects to: https://developer.algorand.org/docs/reference/rest-apis/kmd/#post-v1transactionsign. Looking into kmd might help you create your own key signing system for the SDK.

Also, the SDK does provide some utility functions to convert mnemonics into private keys, but it's not necessary to use these to interact with the SDK. All you need is an account's public key or address to create transactions. As long as you have some way to sign those transactions with the account's private key (either because it's known to the SDK or an external system can sign the transaction), this is perfectly valid.

**Comment by codemaster101** [comment]
Thanks @jasonpaulos, let me try it, see if it works and then post an example here if people in the future would like to use the logic.
