### ISSUE TITLE
Invalid type of total field in the response of getAssetByID()

### ISSUE THREAD

**Issue by ma-spadafora** [algorand/js-algorand-sdk#475]
### Subject of the issue

The field `total` of `AssetParams` returned by `algosdk.Algodv2.getAssetByID()` is always a `number`, even if the ASA has been created with a `bigint` greater than `Number.MAX_SAFE_INTEGER`.

### Your environment

* Software version: `3.0.1.dev`
* Operating System details: `sandbox on macOS`

### Steps to reproduce

1. Create an asset with: `total=2^64-1` and retrieve its identifier (`assetId`)
2. Invoke function `getAssetByID(assetId)` through the sdk.

### Expected behaviour
the field `total` must be a `bigint` with value `18446744073709551615`.

### Actual behaviour
the field `total` is a `number` and its value is rounded to `18446744073709552000`.

**Comment by jasonpaulos** [comment]
In order to maintain compatibility with existing code, we chose not to change the return type of numbers in our responses. If you would like to receive bigints in your response, then you must call the `setIntDecoding` method on the request object (or on the `Algodv2` client if you want to apply a setting to all requests from that client). For example:

```javascript
const client = new algosdk.Algodv2(...);
await client.getAssetByID(...).setIntDecoding(algosdk.IntDecoding.BIGINT).do()
```

The full options for `IntDecoding` are described here: https://algorand.github.io/js-algorand-sdk/enums/intdecoding.html

We recognize this interface is not the most obvious, and the next major version of the SDK will do a better job at addressing bigint return values.
