### ISSUE TITLE
Request failed in Manifest V3

### ISSUE THREAD

**Issue by pauldo-verd** [algorand/js-algorand-sdk#584]
### Subject of the issue

I get an error in `sdk.accountInformation(address).do().catch(log.error)` when building an extension with manifest version 3. It worked in the manifest V2.

```
Error: Browser-only version of superagent could not find XHR
```

### Your environment
- js-algorand-sdk v1.15.0
- Chrome Manifest V3

**Comment by jasonpaulos** [comment]
Hi @pauldo-verd, I don't know much about Chrome Manifest, but it says here that `XMLHttpRequest` is not available in background pages or Service Works: https://developer.chrome.com/docs/extensions/mv3/xhr/

Are you using the SDK in that environment?

**Comment by pauldo-verd** [comment]
Thanks for your quick response.
I'm using `chrome.runtime.sendMessage` on the client to call the SDK's custom methods in the background

**Comment by jasonpaulos** [comment]
The HTTP library we use, `superagent`, uses `XMLHttpRequest` to make HTTP calls. Unfortunately the problem is `XMLHttpRequest` isn't available in your situation, only `fetch` is available.

There is no easy way to get around that. I can think of two solutions:
* The SDK would need to use `fetch` instead of `superagent`. I believe the only place the library is used is in this file: https://github.com/algorand/js-algorand-sdk/blob/18b863be6f4fe435b77c75b62316c0a599d88d68/src/client/urlTokenBaseHTTPClient.ts
* Or, a polyfill for `XMLHttpRequest` that uses `fetch` under the hood would need to be used, but I'm not sure that this exists.

**Comment by pauldo-verd** [comment]
Thanks for your solutions. I will do more research to solve it.
