### ISSUE TITLE
crypto module missing on react native app

### ISSUE THREAD

**Issue by davide99** [algorand/js-algorand-sdk#643]
### Subject of the issue

I'm trying to use the sdk in a react native app. Since the react native doesn't include the node standard library the following error pops up:
The package at "node_modules/algosdk/dist/browser/algosdk.min.js" attempted to import the Node standard library module "crypto".

### Steps to reproduce

1. npx create-expo-app app
2. cd app
3. const algosdk = require('algosdk'); in a js file
4. npm start

Is there a way to fix this?
Thank you

**Comment by jasonpaulos** [comment]
Unfortunately React Native is not a supported environment for this library.

Prior issues have been made that may or may not have helpful workarounds, e.g. https://github.com/algorand/js-algorand-sdk/issues/530

**Comment by barnjamin** [comment]
Another dev ran into a similar issue and wrote up his experience here: https://medium.com/@shrinerp/algosdk-vue-js-webpack-and-node-js-d10014e87a55

**Comment by Blackglade** [comment]
Getting this exact same issue with create-react-app as well.

```
Compiled with problems:X

ERROR in ./node_modules/algosdk/dist/browser/algosdk.min.js 7206:55-72

Module not found: Error: Can't resolve 'crypto' in '/Users/harshbaid/Desktop/algoranddao/node_modules/algosdk/dist/browser'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
```

**Comment by jasonpaulos** [comment]
> Getting this exact same issue with create-react-app as well.

@Blackglade you are seeing that because one of our dependencies, [tweetnacl-js](https://github.com/dchest/tweetnacl-js), uses `require('crypto')` to test if the Node.js `crypto` module is available. However, it is perfectly capable of running in a browser that does not have access to the `crypto` module, it just has to check which environment it's in, then fall back on browser functions if necessary.

This is add odds with your React webpack build, which thinks there must be a problem because it doesn't know about the `crypto` module. You must find some way of telling your React build that it's ok to not have that module. Consider modifying your webpack config to do this, possibly with the [`resolve.fallback`](https://webpack.js.org/configuration/resolve/#resolvefallback) option, e.g.:

```js
module.exports = {
  //...
  resolve: {
    fallback: {
      crypto: false, // do not include a polyfill for crypto
    },
  },
};
```

If you are aware of any better way this issue can be solved, please let us know.

**Comment by Blackglade** [comment]
Yup @jasonpaulos I was able to get around this fairly easily, but it's still a hassle given the fact that I'm using create-react-app which makes editing it's webpack config impossible unless I eject all the scripts. Please see my comments here: https://github.com/algorand/js-algorand-sdk/issues/645

**Comment by davide99** [comment]
I will try @barnjamin solution, it sounds pretty promising. I will keep you up to date.
Thank you

**Comment by davide99** [comment]
I finally got it working:

1. `npm install expo-crypto-polyfills`
2. create a `metro.config.js` file in your root directory
3. write this: `module.exports = {
    resolver: {
      extraNodeModules: require("expo-crypto-polyfills")
    },
  };`
4. `npm install react-native-get-random-values`
5. go to you `App.js`
6. add as its first line `import 'react-native-get-random-values';`

**Comment by jasonpaulos** [comment]
I just wanted to say that I've opened #707, which should fix the error about a missing `crypto` package.
